apiVersion: apps/v1
kind: Deployment
metadata:
  name: waves-voting-api-deployment
  namespace: waves-voting-prod
  labels:
    app: waves-voting-api
spec:
  replicas: 1
  selector:
    matchLabels:
      role: waves-voting-api
      environment: prod
  template:
    metadata:
      labels:
        role: waves-voting-api
        environment: prod
    spec:
      containers:
      - name: waves-voting
        image: registry.gitlab.com/trustamust/waves-voting:2.2.28
        env:
          - name: NODE_ENV
            value: production
          - name: DB_HOST
            value: "mongo-0.mongo.kube-mongo:27017,mongo-1.mongo.kube-mongo:27017,mongo-2.mongo.kube-mongo:27017"
          - name: DB_NAME
            value: waves-voting-prod?replicaSet=rs0
          - name: MINIO_HOST
            value: "minio.default"
          - name: MINIO_BUCKET
            value: trustamust-prod
          - name: MINIO_ACCESS_KEY
            value: minio
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: prod-secrets
                key: minio_secret_key
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: prod-secrets
                key: jwt_secret
          - name: VOTING_TICKER
            value: WCT
          - name: VOTING_ASSET_ID
            value: DHgwrRvVyqJsepd32YbBqUeDH4GJ1N984X8QoekjgH8J
          - name: VOTING_MAXIMUM_RANK
            value: "100"
          - name: SNAPSHOT_CRON_PATTERN
            value: "*/1 * * * *"
          - name: CLEAN_UP_CRON_PATTERN
            value: "*/1 * * * *"
          - name: WAVES_NODE_ADDRESS 
            value: "http://178.62.48.207:6869"
          - name: DATA_PROVIDER_ID 
            value: 3PMsU8jxAUKoGxNoCsAQ49ncuEpRYFD9FBp
          - name: DATA_PROVIDER_SEED
            valueFrom:
              secretKeyRef:
                name: prod-secrets
                key: data_provider_seed
          - name: VOTING_ASSET_DECIMAL_PLACES
            value: "2"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: gitlab-auth
---
apiVersion: v1
kind: Service
metadata:
  name: waves-voting-api
  namespace: waves-voting-prod
  labels:
    name: waves-voting-api
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None
  selector:
    role: waves-voting-api
    environment: prod